window.Atoms = window.Atoms || {};

window.Atoms.defaultConfig = Object.freeze({
  width: 7,
  height: 7,
  depth: 7,
  restLength: 56,
  atomRadius: 7,
  scenePreset: "molecule",
  pinLayout: "corners",
  material: "molecular",
  physicsMode: "force",
  stiffness: 0.24,
  shearStiffness: 0.16,
  springDamping: 0.16,
  shearDamping: 0.12,
  bendStiffness: 0.08,
  bendDamping: 0.08,
  atomMass: 1,
  releaseEnergy: 0.85,
  dragStrength: 1,
  mouseStiffness: 2.8,
  mouseDamping: 0.4,
  mouseMaxForce: 90,
  dragMaxStepScale: 1.15,
  dragMaxSubsteps: 18,
  strainLimitEnabled: true,
  maxStretchFactor: 1.75,
  minStretchFactor: 0.35,
  strainLimitStiffness: 0.85,
  panelAreaMinFactor: 0.16,
  panelAreaStiffness: 0.25,
  collisionEnabled: false,
  collisionRadiusScale: 1.6,
  collisionStiffness: 0.65,
  collisionDamping: 0.35,
  collisionPasses: 1,
  allowCornerPinEditing: false,
  gravityEnabled: false,
  gravityStrength: 0.18,
  windProfile: "calm",
  windEnabled: false,
  windDirection: "z+",
  windStrength: 0.6,
  windTurbulence: 0.75,
  windScale: 220,
  windSpeed: 1.2,
  windDrag: 0.7,
  windFlutter: 0.45,
  windResponse: 1,
  damping: 0.998,
  iterations: 4,
  physicsRate: 60,
  fastBending: true,
  fastLargeGridAtoms: true,
  sortBonds: true,
  sortAtoms: true,
  showAtoms: true,
  showBonds: true,
  simpleBondColors: false,
  showDiagnostics: true,
  showSurfaces: false,
  surfaceRenderer: "webgl",
  showSurfaceEdges: false,
  surfaceSide: "both",
  surfaceStyle: "tint",
  surfaceTextureImage: null,
  surfaceTextureName: "",
  surfaceFrontTextureImage: null,
  surfaceFrontTextureName: "",
  surfaceBackTextureImage: null,
  surfaceBackTextureName: "",
  mirrorBackTexture: true,
  flipBackTexture: false,
  surfaceOpacity: 0.22,
  surfaceLighting: true,
  surfaceLightingModel: "standard",
  surfaceFabricEnabled: false,
  fabricWeaveStrength: 0,
  surfaceFoldShadingEnabled: false,
  foldShadingStrength: 0,
  sunAzimuth: 35,
  sunElevation: 35,
  sunIntensity: 0.75,
  sunAmbient: 0.45,
  showWindField: false,
  showCollisionDebug: false,
  atomDepthShading: 1,
  energyUpdateRate: 1,
  energyScale: 0.12,
  minZoom: 0.35,
  maxZoom: 3.2,
});

window.Atoms.windProfiles = Object.freeze({
  calm: Object.freeze({
    label: "Calm",
    windEnabled: false,
    windDirection: "z+",
    windStrength: 0,
    windTurbulence: 0.35,
    windScale: 260,
    windSpeed: 0.6,
    windDrag: 0.45,
    windFlutter: 0.1,
  }),
  breeze: Object.freeze({
    label: "Breeze",
    windEnabled: true,
    windDirection: "z+",
    windStrength: 0.55,
    windTurbulence: 0.55,
    windScale: 360,
    windSpeed: 0.9,
    windDrag: 0.55,
    windFlutter: 0.25,
  }),
  gusty: Object.freeze({
    label: "Gusty",
    windEnabled: true,
    windDirection: "z+",
    windStrength: 1.05,
    windTurbulence: 1.15,
    windScale: 240,
    windSpeed: 2.1,
    windDrag: 0.9,
    windFlutter: 0.8,
  }),
  flag: Object.freeze({
    label: "Flag",
    windEnabled: true,
    windDirection: "x+",
    windStrength: 1.15,
    windTurbulence: 1.05,
    windScale: 260,
    windSpeed: 2.6,
    windDrag: 0.95,
    windFlutter: 1.05,
  }),
  storm: Object.freeze({
    label: "Storm",
    windEnabled: true,
    windDirection: "z+",
    windStrength: 1.85,
    windTurbulence: 1.55,
    windScale: 170,
    windSpeed: 4.4,
    windDrag: 1.25,
    windFlutter: 1.45,
  }),
});

window.Atoms.windProfileKeys = Object.freeze([
  "windEnabled",
  "windDirection",
  "windStrength",
  "windTurbulence",
  "windScale",
  "windSpeed",
  "windDrag",
  "windFlutter",
]);

window.Atoms.materialProperties = Object.freeze({
  molecular: Object.freeze({
    label: "Molecular",
    stiffness: 0.32,
    shearStiffness: 0.16,
    springDamping: 0.12,
    shearDamping: 0.08,
    bendStiffness: 0.16,
    bendDamping: 0.06,
    atomMass: 1,
    mouseStiffness: 2.8,
    mouseDamping: 0.4,
    windResponse: 0.45,
    surfaceLightingModel: "standard",
    surfaceFabricEnabled: false,
    fabricWeaveStrength: 0,
    surfaceFoldShadingEnabled: false,
    foldShadingStrength: 0,
  }),
  cloth: Object.freeze({
    label: "Cloth",
    stiffness: 0.22,
    shearStiffness: 0.18,
    springDamping: 0.18,
    shearDamping: 0.16,
    bendStiffness: 0.025,
    bendDamping: 0.04,
    atomMass: 0.75,
    mouseStiffness: 2.4,
    mouseDamping: 0.55,
    windResponse: 1,
    surfaceLightingModel: "cloth",
    surfaceFabricEnabled: true,
    fabricWeaveStrength: 0.08,
    surfaceFoldShadingEnabled: true,
    foldShadingStrength: 0.08,
  }),
  rubber: Object.freeze({
    label: "Rubber",
    stiffness: 0.18,
    shearStiffness: 0.22,
    springDamping: 0.32,
    shearDamping: 0.28,
    bendStiffness: 0.09,
    bendDamping: 0.14,
    atomMass: 1.1,
    mouseStiffness: 2.2,
    mouseDamping: 0.85,
    windResponse: 0.8,
    surfaceLightingModel: "standard",
    surfaceFabricEnabled: false,
    fabricWeaveStrength: 0,
    surfaceFoldShadingEnabled: false,
    foldShadingStrength: 0,
  }),
  gel: Object.freeze({
    label: "Gel",
    stiffness: 0.09,
    shearStiffness: 0.08,
    springDamping: 0.42,
    shearDamping: 0.36,
    bendStiffness: 0.035,
    bendDamping: 0.2,
    atomMass: 0.8,
    mouseStiffness: 1.4,
    mouseDamping: 1.1,
    windResponse: 0.7,
    surfaceLightingModel: "standard",
    surfaceFabricEnabled: false,
    fabricWeaveStrength: 0,
    surfaceFoldShadingEnabled: false,
    foldShadingStrength: 0,
  }),
  heavy: Object.freeze({
    label: "Heavy lattice",
    stiffness: 0.42,
    shearStiffness: 0.28,
    springDamping: 0.22,
    shearDamping: 0.18,
    bendStiffness: 0.22,
    bendDamping: 0.12,
    atomMass: 4,
    mouseStiffness: 4.2,
    mouseDamping: 1.2,
    windResponse: 0.25,
    surfaceLightingModel: "standard",
    surfaceFabricEnabled: false,
    fabricWeaveStrength: 0,
    surfaceFoldShadingEnabled: false,
    foldShadingStrength: 0,
  }),
});

window.Atoms.materialKeys = Object.freeze([
  "stiffness",
  "shearStiffness",
  "springDamping",
  "shearDamping",
  "bendStiffness",
  "bendDamping",
  "atomMass",
  "mouseStiffness",
  "mouseDamping",
  "windResponse",
  "surfaceLightingModel",
  "surfaceFabricEnabled",
  "fabricWeaveStrength",
  "surfaceFoldShadingEnabled",
  "foldShadingStrength",
]);

window.Atoms.scenePresets = Object.freeze({
  molecule: Object.freeze({
    label: "Molecule",
    width: 7,
    height: 7,
    depth: 7,
    restLength: 56,
    atomRadius: 7,
    pinLayout: "corners",
    material: "molecular",
    collisionEnabled: false,
    collisionRadiusScale: 1.6,
    collisionStiffness: 0.65,
    collisionPasses: 1,
    gravityEnabled: false,
    gravityStrength: 0.18,
    windProfile: "calm",
    windEnabled: false,
    windDirection: "z+",
    windStrength: 0.35,
    windTurbulence: 0.65,
    windScale: 220,
    windSpeed: 1,
    windDrag: 0.45,
    windFlutter: 0.3,
    physicsMode: "force",
    showAtoms: true,
    showBonds: true,
    showSurfaces: false,
    surfaceRenderer: "webgl",
  }),
  flag: Object.freeze({
    label: "Flag / cloth",
    width: 14,
    height: 7,
    depth: 1,
    restLength: 42,
    atomRadius: 6,
    pinLayout: "leftEdge",
    material: "cloth",
    collisionEnabled: true,
    collisionRadiusScale: 1.35,
    collisionStiffness: 0.45,
    collisionPasses: 2,
    gravityEnabled: true,
    gravityStrength: 0.18,
    windProfile: "flag",
    windEnabled: true,
    windDirection: "x+",
    windStrength: 1.15,
    windTurbulence: 1.05,
    windScale: 260,
    windSpeed: 2.6,
    windDrag: 0.95,
    windFlutter: 1.05,
    physicsMode: "force",
    showAtoms: false,
    showBonds: false,
    showSurfaces: true,
    surfaceRenderer: "webgl",
    surfaceLightingModel: "cloth",
    surfaceFabricEnabled: true,
    fabricWeaveStrength: 0.08,
    surfaceFoldShadingEnabled: true,
    foldShadingStrength: 0.08,
  }),
  gelCube: Object.freeze({
    label: "Soft gel cube",
    width: 8,
    height: 8,
    depth: 8,
    restLength: 48,
    atomRadius: 7,
    pinLayout: "corners",
    material: "gel",
    collisionEnabled: false,
    collisionRadiusScale: 1.6,
    collisionStiffness: 0.6,
    collisionPasses: 1,
    gravityEnabled: false,
    gravityStrength: 0.12,
    windProfile: "calm",
    windEnabled: false,
    windDirection: "z+",
    windStrength: 0.32,
    windTurbulence: 0.7,
    windScale: 220,
    windSpeed: 1,
    windDrag: 0.55,
    windFlutter: 0.35,
    physicsMode: "force",
    showAtoms: true,
    showBonds: true,
    showSurfaces: false,
    surfaceRenderer: "webgl",
  }),
  heavyLattice: Object.freeze({
    label: "Heavy lattice",
    width: 9,
    height: 9,
    depth: 5,
    restLength: 50,
    atomRadius: 7,
    pinLayout: "corners",
    material: "heavy",
    collisionEnabled: false,
    collisionRadiusScale: 1.4,
    collisionStiffness: 0.75,
    collisionPasses: 1,
    gravityEnabled: true,
    gravityStrength: 0.12,
    windProfile: "calm",
    windEnabled: false,
    windDirection: "z+",
    windStrength: 0.4,
    windTurbulence: 0.6,
    windScale: 260,
    windSpeed: 0.8,
    windDrag: 0.35,
    windFlutter: 0.25,
    physicsMode: "force",
    showAtoms: true,
    showBonds: true,
    showSurfaces: false,
    surfaceRenderer: "webgl",
  }),
});

window.Atoms.scenePresetKeys = Object.freeze([
  "width",
  "height",
  "depth",
  "restLength",
  "atomRadius",
  "pinLayout",
  "material",
  "collisionEnabled",
  "collisionRadiusScale",
  "collisionStiffness",
  "collisionPasses",
  "gravityEnabled",
  "gravityStrength",
  "windProfile",
  "windEnabled",
  "windDirection",
  "windStrength",
  "windTurbulence",
  "windScale",
  "windSpeed",
  "windDrag",
  "windFlutter",
  "physicsMode",
  "showAtoms",
  "showBonds",
  "showSurfaces",
  "surfaceRenderer",
]);

window.Atoms.clamp = function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
};

window.Atoms.readNumber = function readNumber(value, fallback, min, max) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    return fallback;
  }
  return window.Atoms.clamp(parsed, min, max);
};
