window.Atoms = window.Atoms || {};

window.Atoms.defaultConfig = Object.freeze({
  width: 7,
  height: 7,
  depth: 7,
  restLength: 56,
  atomRadius: 7,
  scenePreset: "molecule",
  pinLayout: "corners",
  material: "molecular",
  physicsMode: "spring",
  stiffness: 0.24,
  shearStiffness: 0.16,
  springDamping: 0.16,
  shearDamping: 0.12,
  bendStiffness: 0.08,
  bendDamping: 0.08,
  atomMass: 1,
  releaseEnergy: 0.85,
  dragStrength: 1,
  mouseStiffness: 2.8,
  mouseDamping: 0.4,
  allowCornerPinEditing: false,
  gravityEnabled: false,
  gravityStrength: 0.18,
  windEnabled: false,
  windDirection: "z+",
  windStrength: 0.16,
  windTurbulence: 0.75,
  windScale: 220,
  windSpeed: 1.2,
  windDrag: 0.22,
  windFlutter: 0.45,
  damping: 0.998,
  iterations: 4,
  physicsRate: 60,
  fastBending: true,
  fastLargeGridAtoms: true,
  sortBonds: true,
  sortAtoms: true,
  simpleBondColors: false,
  showDiagnostics: true,
  atomDepthShading: 1,
  energyUpdateRate: 1,
  energyScale: 0.12,
  minZoom: 0.35,
  maxZoom: 3.2,
});

window.Atoms.materialProperties = Object.freeze({
  molecular: Object.freeze({
    label: "Molecular",
    stiffness: 0.32,
    shearStiffness: 0.16,
    springDamping: 0.12,
    shearDamping: 0.08,
    bendStiffness: 0.16,
    bendDamping: 0.06,
    atomMass: 1,
    mouseStiffness: 2.8,
    mouseDamping: 0.4,
  }),
  cloth: Object.freeze({
    label: "Cloth",
    stiffness: 0.22,
    shearStiffness: 0.18,
    springDamping: 0.18,
    shearDamping: 0.16,
    bendStiffness: 0.025,
    bendDamping: 0.04,
    atomMass: 0.75,
    mouseStiffness: 2.4,
    mouseDamping: 0.55,
  }),
  rubber: Object.freeze({
    label: "Rubber",
    stiffness: 0.18,
    shearStiffness: 0.22,
    springDamping: 0.32,
    shearDamping: 0.28,
    bendStiffness: 0.09,
    bendDamping: 0.14,
    atomMass: 1.1,
    mouseStiffness: 2.2,
    mouseDamping: 0.85,
  }),
  gel: Object.freeze({
    label: "Gel",
    stiffness: 0.09,
    shearStiffness: 0.08,
    springDamping: 0.42,
    shearDamping: 0.36,
    bendStiffness: 0.035,
    bendDamping: 0.2,
    atomMass: 0.8,
    mouseStiffness: 1.4,
    mouseDamping: 1.1,
  }),
  heavy: Object.freeze({
    label: "Heavy lattice",
    stiffness: 0.42,
    shearStiffness: 0.28,
    springDamping: 0.22,
    shearDamping: 0.18,
    bendStiffness: 0.22,
    bendDamping: 0.12,
    atomMass: 4,
    mouseStiffness: 4.2,
    mouseDamping: 1.2,
  }),
});

window.Atoms.materialKeys = Object.freeze([
  "stiffness",
  "shearStiffness",
  "springDamping",
  "shearDamping",
  "bendStiffness",
  "bendDamping",
  "atomMass",
  "mouseStiffness",
  "mouseDamping",
]);

window.Atoms.scenePresets = Object.freeze({
  molecule: Object.freeze({
    label: "Molecule",
    width: 7,
    height: 7,
    depth: 7,
    restLength: 56,
    atomRadius: 7,
    pinLayout: "corners",
    material: "molecular",
    gravityEnabled: false,
    gravityStrength: 0.18,
    windEnabled: false,
    windDirection: "z+",
    windStrength: 0.12,
    windTurbulence: 0.65,
    windScale: 220,
    windSpeed: 1,
    windDrag: 0.18,
    windFlutter: 0.3,
    physicsMode: "spring",
  }),
  flag: Object.freeze({
    label: "Flag / cloth",
    width: 14,
    height: 7,
    depth: 1,
    restLength: 42,
    atomRadius: 6,
    pinLayout: "leftEdge",
    material: "cloth",
    gravityEnabled: true,
    gravityStrength: 0.18,
    windEnabled: true,
    windDirection: "z+",
    windStrength: 0.2,
    windTurbulence: 0.9,
    windScale: 260,
    windSpeed: 1.35,
    windDrag: 0.28,
    windFlutter: 0.9,
    physicsMode: "spring",
  }),
  gelCube: Object.freeze({
    label: "Soft gel cube",
    width: 8,
    height: 8,
    depth: 8,
    restLength: 48,
    atomRadius: 7,
    pinLayout: "corners",
    material: "gel",
    gravityEnabled: false,
    gravityStrength: 0.12,
    windEnabled: false,
    windDirection: "z+",
    windStrength: 0.1,
    windTurbulence: 0.7,
    windScale: 220,
    windSpeed: 1,
    windDrag: 0.2,
    windFlutter: 0.35,
    physicsMode: "spring",
  }),
  heavyLattice: Object.freeze({
    label: "Heavy lattice",
    width: 9,
    height: 9,
    depth: 5,
    restLength: 50,
    atomRadius: 7,
    pinLayout: "corners",
    material: "heavy",
    gravityEnabled: true,
    gravityStrength: 0.12,
    windEnabled: false,
    windDirection: "z+",
    windStrength: 0.12,
    windTurbulence: 0.6,
    windScale: 260,
    windSpeed: 0.8,
    windDrag: 0.12,
    windFlutter: 0.25,
    physicsMode: "spring",
  }),
});

window.Atoms.scenePresetKeys = Object.freeze([
  "width",
  "height",
  "depth",
  "restLength",
  "atomRadius",
  "pinLayout",
  "material",
  "gravityEnabled",
  "gravityStrength",
  "windEnabled",
  "windDirection",
  "windStrength",
  "windTurbulence",
  "windScale",
  "windSpeed",
  "windDrag",
  "windFlutter",
  "physicsMode",
]);

window.Atoms.clamp = function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
};

window.Atoms.readNumber = function readNumber(value, fallback, min, max) {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) {
    return fallback;
  }
  return window.Atoms.clamp(parsed, min, max);
};
